---

- name: install packages
  apt:
    name:
      - autoconf
      - bison
      - build-essential
      - curl
      - ffmpeg
      - git
      - imagemagick
      - libcurl4
      - libcurl4-openssl-dev
      - libffi-dev
      - libgdbm-dev
      - libncurses5-dev
      - libreadline-dev
      - libreadline-dev
      - libssl-dev
      - libyaml-dev
      - python2
      - python3
      - python3-pip
      - python3-tmuxp
      - vim-gui-common
      - wget
      - xclip
      - zlib1g-dev
    update_cache: true
