---

- name: install repo
  copy:
    dest: /etc/apt/sources.list.d/pgdg.list
    content: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main

- name: install pg client
  apt:
    name:
      - postgresql-client-14
      - libpq-dev
    update_cache: true
